services:
  redis:
    container_name: redis
    image: valkey/valkey:7.2.9-alpine
    restart: unless-stopped
    ports: [ "127.0.0.1:9736:6379" ]
    volumes:
      - "redis-data:/data:delegated"
      - "./redis/redis.conf:/etc/redis.conf"
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "127.0.0.1:8088:8080"
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - "./config/searxng:/etc/searxng"
volumes:
  redis-data:
