# Provides helper methods for HTTP interactions used by the OllamaChat
# library.  The module is mixed into various classes (e.g. `OllamaChat::Chat`)
# to give them access to a convenient, configuration‑aware HTTP client.
#
# The primary responsibilities are:
#
# * Build a hash of HTTP options (e.g. SSL verification and proxy
#   settings) based on the current configuration.
# * Perform a GET request with those options, optionally using a cache
#   and debugging information.
#
# The module is deliberately lightweight – it delegates the actual network
# call to `OllamaChat::Utils::Fetcher`.
module OllamaChat::HTTPHandling
  # Returns a hash of HTTP options suitable for `Net::HTTP` or a
  # compatible client.
  #
  # The options include:
  # * `:ssl_verify_peer` – a boolean that disables peer verification for
  #   hostnames listed in the configuration’s `ssl_no_verify` set.
  # * `:proxy` – the proxy URL if one is configured.
  #
  # @param url [String] the URL for which the options should be
  #   generated.
  # @return [Hash] a hash containing the HTTP options.
  def http_options(url)
    options = {}
    if ssl_no_verify = config.ssl_no_verify?
      hostname = URI.parse(url).hostname
      options |= { ssl_verify_peer: !ssl_no_verify.include?(hostname) }
    end
    if proxy = config.proxy?
      options |= { proxy: }
    end
    options
  end

  # Performs an HTTP GET request.
  #
  # The method merges the caller‑supplied headers with the headers
  # configured in `config.request_headers?`.  It then delegates to
  # `OllamaChat::Utils::Fetcher.get`, passing along any cache or debug
  # flags and the HTTP options generated by `http_options`.
  #
  # @param url [String] the target URL.
  # @param headers [Hash] optional additional headers.
  # @param reraise [Boolean] whether to re‑raise errors from the fetcher.
  # @param cache [Object] optional cache object to use.
  # @yield [IO] yields a temporary file handle for the caller to consume.
  # @return [Object] the result of the block or the fetcher.
  def get_url(url, headers: nil, reraise: false, cache: nil, &block)
    headers = config.request_headers?.to_h | headers
    OllamaChat::Utils::Fetcher.get(
      url,
      headers:      ,
      cache:        ,
      debug:        ,
      reraise:      ,
      http_options: http_options(OllamaChat::Utils::Fetcher.normalize_url(url)),
      &block
    )
  end
end
